- name: Set OS family mapping fact
  ansible.builtin.set_fact:
    aws_ssm_plugin__os_family_mapping:
      Debian:
        group: ubuntu
        type: deb
      RedHat:
        group: linux
        type: rpm

- name: Set CPU arch mapping fact
  ansible.builtin.set_fact:
    aws_ssm_plugin__cpu_arch_mapping:
      x86_64: 64bit
      aarch64: arm64

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Set packages to install fact
  when: aws_ssm_plugin__packages is not defined
  ansible.builtin.set_fact:
    aws_ssm_plugin__packages: "{{ _aws_ssm_plugin__packages | list }}"

- name: Install dependencies
  ansible.builtin.package:
    name: "{{ aws_ssm_plugin__packages }}"
    state: present
  become: true

- name: Get installed version
  ansible.builtin.shell:
    executable: /usr/bin/bash
    cmd: |
      set -euo pipefail
      if command -v session-manager-plugin &> /dev/null; then
        session-manager-plugin --version
      fi
  changed_when: false
  register: aws_ssm_plugin__get_installed_version

- name: Set installed version fact
  ansible.builtin.set_fact:
    aws_ssm_plugin__installed_version: >-
      {{ aws_ssm_plugin__get_installed_version.stdout | regex_search(".+\..+\..+") }}

- name: Print installed version
  ansible.builtin.debug:
    var: aws_ssm_plugin__installed_version

- name: Set empty archive URL parts fact
  ansible.builtin.set_fact:
    aws_ssm_plugin__archive_url_parts: []

- name: Set archive URL parts fact for target present
  when: aws_ssm_plugin__version == "present" and aws_ssm_plugin__installed_version == ""
  ansible.builtin.set_fact:
    aws_ssm_plugin__archive_url_parts:
      - https://s3.amazonaws.com/session-manager-downloads/plugin/latest/
      - "{{ aws_ssm_plugin__os_family_mapping[ansible_os_family]['group'] }}"
      - _
      - "{{ aws_ssm_plugin__cpu_arch_mapping[ansible_architecture] }}"
      - /session-manager-plugin.
      - "{{ aws_ssm_plugin__os_family_mapping[ansible_os_family]['type'] }}"

- name: Determine archive URL parts fact for target latest
  when: aws_ssm_plugin__version == "latest"
  block:
    - name: Get latest version
      ansible.builtin.shell:
        executable: /usr/bin/bash
        cmd: |
          set -euo pipefail
          curl --silent --fail-with-body {{ release_url }} \
            | sed -n -E 's/.*"tag_name": "(.+)",.*/\1/p'
      vars:
        release_url: https://api.github.com/repos/aws/session-manager-plugin/releases/latest
      changed_when: false
      register: aws_ssm_plugin__get_latest_version

    - name: Set latest version fact
      ansible.builtin.set_fact:
        aws_ssm_plugin__latest_version: >-
          {{ aws_ssm_plugin__get_latest_version.stdout | regex_search(".+\..+\..+") }}

    - name: Print latest version fact
      ansible.builtin.debug:
        var: aws_ssm_plugin__latest_version

    - name: Set archive URL fact for target latest
      when: aws_ssm_plugin__installed_version != aws_ssm_plugin__latest_version
      ansible.builtin.set_fact:
        aws_ssm_plugin__archive_url_parts:
          - https://s3.amazonaws.com/session-manager-downloads/plugin/latest/
          - "{{ aws_ssm_plugin__os_family_mapping[ansible_os_family]['group'] }}"
          - _
          - "{{ aws_ssm_plugin__cpu_arch_mapping[ansible_architecture] }}"
          - /session-manager-plugin.
          - "{{ aws_ssm_plugin__os_family_mapping[ansible_os_family]['type'] }}"

- name: Set archive URL fact from parts
  ansible.builtin.set_fact:
    aws_ssm_plugin__archive_url: "{{ aws_ssm_plugin__archive_url_parts | join }}"

- name: Print archive URL fact
  ansible.builtin.debug:
    var: aws_ssm_plugin__archive_url

- name: Install
  when: aws_ssm_plugin__archive_url != ""
  become: true
  block:
    - name: Create tmp dir
      ansible.builtin.tempfile:
        state: directory
      register: aws_ssm_plugin__tmp_dir

    - name: Download archive
      ansible.builtin.get_url:
        url: "{{ aws_ssm_plugin__archive_url }}"
        dest: "{{ aws_ssm_plugin__tmp_dir.path }}/aws-ssm-plugin-archive"
        force: true
        mode: u=rw,g=,o=
      register: aws_ssm_plugin__download_archive

    - name: Install (Debian)
      when: ansible_os_family == "Debian"
      ansible.builtin.apt:
        deb: "{{ aws_ssm_plugin__download_archive.dest }}"

    - name: Install (RedHat)
      when: ansible_os_family == "RedHat"
      ansible.builtin.dnf:
        name: "{{ aws_ssm_plugin__download_archive.dest }}"
        state: present

    - name: Check executable
      ansible.builtin.command:
        cmd: session-manager-plugin --version
      changed_when: false
