- name: Verify
  hosts: all

  tasks:
    - name: Get installed version
      ansible.builtin.shell:
        executable: /usr/bin/bash
        cmd: |
          set -euo pipefail
          if command -v session-manager-plugin &> /dev/null; then
            session-manager-plugin --version
          fi
      changed_when: false
      register: get_installed_version

    - name: Set installed version fact
      ansible.builtin.set_fact:
        installed_version: >-
          {{ get_installed_version.stdout | regex_search(".+\..+\..+") }}

    - name: Get latest version
      ansible.builtin.shell:
        executable: /usr/bin/bash
        cmd: |
          set -euo pipefail
          curl --silent --fail-with-body {{ release_url }} \
            | sed -n -E 's/.*"tag_name": "(.+)",.*/\1/p'
      vars:
        release_url: https://api.github.com/repos/aws/session-manager-plugin/releases/latest
      changed_when: false
      register: get_latest_version

    - name: Set latest version fact
      ansible.builtin.set_fact:
        latest_version: >-
          {{ get_latest_version.stdout | regex_search(".+\..+\..+") }}

    - name: Assert installed version correct
      ansible.builtin.assert:
        that:
          - installed_version == latest_version
        fail_msg: >-
          `installed_version` is "{{ installed_version }}",
          but must be "{{ latest_version }}".
